// src/components/skip-link.vue
<script lang="ts" setup>
import { useI18n } from "@/lib/i18n/use-i18n";
import { NuxtLink } from "#components";

const { t } = useI18n();

const id = "main-content";
const hash = "#" + id;

/**
 * @see https://bugzilla.mozilla.org/show_bug.cgi?id=308064
 */
function onClick() {
	const element = document.getElementById(id);
	element?.focus();
}
</script>

<template>
	<NuxtLink
		class="fixed -translate-y-full rounded bg-white px-4 py-3 transition focus:translate-y-0"
		:href="{ hash }"
		@click="onClick"
	>
		{{ t("common.skip-to-main-content") }}
	</NuxtLink>
</template>

// components/skip-link.tsx
"use client";

import type { ReactNode } from "react";

import { Link } from "@/components/link";
import { createHref } from "@/lib/create-href";

interface SkipLinkProps {
	children: ReactNode;
	id?: string;
	targetId: string;
}

export function SkipLink(props: Readonly<SkipLinkProps>): ReactNode {
	const { children, id, targetId } = props;

	/**
	 * @see https://bugzilla.mozilla.org/show_bug.cgi?id=308064
	 */
	function onPress() {
		document.getElementById(targetId)?.focus();
	}

	return (
		<Link
			className="fixed z-50 m-1 translate-y-[calc(-100%-0.25rem)] rounded bg-white px-4 py-3 text-brand-950 transition focus-visible:translate-y-0 focus-visible:focus-outline"
			href={createHref({ hash: targetId })}
			id={id}
			onPress={onPress}
		>
			{children}
		</Link>
	);
}
