// components/skip-link.vue
<script lang="ts" setup>
const props = defineProps<{
	targetId: string;
}>();

/**
 * @see https://bugzilla.mozilla.org/show_bug.cgi?id=308064
 */
function onClick() {
	const element = document.getElementById(props.targetId);
	element?.focus();
}
</script>

<template>
	<NuxtLink
		class="fixed -translate-y-full rounded-md bg-background px-4 py-3 text-on-background transition focus:translate-y-0"
		:href="{ hash: `#${props.targetId}` }"
		@click="onClick"
	>
		<slot />
	</NuxtLink>
</template>

// src/components/skip-link.tsx
import { Link } from "next-intl";
import { type ReactNode } from "react";

interface SkipLinkProps {
	children: ReactNode;
	id?: string;
	targetId: string;
}

export function SkipLink(props: SkipLinkProps): JSX.Element {
	const { children, id, targetId } = props;

	/**
	 * @see https://bugzilla.mozilla.org/show_bug.cgi?id=308064
	 */
	function onClick() {
		document.getElementById(targetId)?.focus();
	}

	return (
		<Link
			className="fixed -translate-y-full rounded bg-neutral-50 px-4 py-3 text-neutral-900 transition focus:translate-y-0"
			href={{ hash: targetId }}
			id={id}
			onClick={onClick}
		>
			{children}
		</Link>
	);
}
